kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: java-app-config
  namespace: jroordinkbd-dev
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'java-app:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
        name: java-app-auth
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/jroordink/example-java-app.git'
      ref: main
    contextDir: /
  runPolicy: Serial