kind: Service
apiVersion: v1
metadata:
  name: java-app
  namespace: jroordinkbd-dev
  labels:
    app: example-java-app
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: java-app