apiVersion: tekton.dev/v1
kind: Task
metadata:
  creationTimestamp: '2023-11-22T13:36:54Z'
  generation: 4
  managedFields:
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:steps': {}
      manager: Mozilla
      operation: Update
      time: '2023-11-23T10:17:18Z'
  name: java-app-prd-image
  namespace: jroordinkbd-dev
  resourceVersion: '3434672661'
  uid: 4af328ef-c0ed-4554-a259-44f23699f66b
spec:
  steps:
    - computeResources: {}
      image: 'quay.io/openshift/origin-cli:latest'
      name: promote-image
      script: |
        #!/usr/bin/env sh
        cd $(workspaces.java-source.path)
        cd example-java-app
        oc tag java-app:latest java-app:prd 
