apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: '2023-11-22T12:31:52Z'
  generation: 3
  managedFields:
    - apiVersion: triggers.tekton.dev/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
      manager: Mozilla
      operation: Update
      time: '2023-11-22T13:48:21Z'
  name: java-app-trigger-binding
  namespace: jroordinkbd-dev
  resourceVersion: '3431671681'
  uid: d5defc5a-8b9f-4956-9991-897848692a83
spec:
  params:
    - name: gitrevision
      value: $(body.pull_request.head.sha)
